#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

char chr(int val) {
  val = val % 256;
  if (val < 0) val += 256;

  if (val == 0) val = ' ';

  return val;
}

task main() {
  bool left = false,
    right = false,
    lastLeft = false,
    lastRight = false;

  int st = 0;

  char line[17];

  line[16] = 0;

  while (true) {
    left = nLCDButtons & kButtonLeft;
    right = nLCDButtons & kButtonRight;

    if (left && !lastLeft) {
      st = (st - 16) % 256;

      if (st < 0) st += 256;
    }

    if (right && !lastRight) {
      st = (st + 16) % 256;
    }

    if (nLCDButtons & kButtonCenter) {
      clearLCDLine(0);
      displayLCDCenteredString(0, "Start:");

      clearLCDLine(1);
      displayLCDNumber(1, 0, st);
    }
    else {
	    for (int i = 0; i < 16; i++)
	      line[i] = chr(st + i);

	    clearLCDLine(0);
	    displayLCDString(0, 0, line);

	    for (int i = 0; i < 16; i++)
	      line[i] = chr(line[i] + 16);

	    clearLCDLine(1);
	    displayLCDString(1, 0, line);

	    lastLeft = left;
	    lastRight = right;
	  }

    wait1Msec(50);
  }
}
