#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  flyEnc,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           intake,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           brWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           mrWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           frWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           lFly,          tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,           rFly,          tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           flWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           mlWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           blWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          lift,          tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define RKCOMP_LCD //Enable LCD stuff in rkCompetition
//#define RKCOMP_DEBUG //Comment to disable debug mode

#define RKCOMP_DEBUG_MENU_COND vexRT[Btn8R]
#define RKCOMP_DEBUG_DISABLE_COND vexRT[Btn8U]
#define RKCOMP_DEBUG_AUTON_COND vexRT[Btn8L]
#define RKCOMP_DEBUG_DRIVER_COND vexRT[Btn8D]
#define RKCOMP_DEBUG_RESTART_COND vexRT[Btn6U]

#include "rkUtil/lib.h"

#include "rkLogic/dlatch.h"

#include "rkLcd/lib.h"

#include "rkControl/base.h"
#include "rkControl/diff.h"
#include "rkControl/kalman.h"
#include "rkControl/tbh.h"
#include "rkControl/tbhController.h"

#include "rkCompetition/lib.h"

//#define USE_PRELOAD_AUTON //Comment to start the intake immediately in auton

int flyDir;

float flyPwr[4] = {0, 600, 700, 950},
	kI = .5,
	kD = .05;

string flyPwrNames[4] = {
	"Off",
	"Short Power",
	"Mid Power",
	"Long Power",
};

const float autonFlyPwr = 950,
	velThresh = 50,
	accelThresh = 100;

ADiff flyDiff, fly2Diff, liftDiff, lift2Diff;
KFlt fly2Flt;
Tbh flyTbh;
TbhController flyCtl;

void lcdDispPwr() {
	displayLCDCenteredString(0, flyPwrNames[flyDir]);
	displayLCDNumber(1, 0, flyPwr[flyDir]);
}

task lcd() {
	const float flyPwrIncrement = 5;
	const word battThresh = 7800;

	bool dispPwr = false,
		flash = false,
		forceBattWarning = true;

	float pwrBtns;
	long time = nSysTime, flashTs = time, dispPwrTs = nSysTime;
	string str;

	DLatch dismissWarningLatch;

	while (true) {
		time = nSysTime;

		if (nImmediateBatteryLevel < battThresh) {
			if ((flashTs - time) >= 500) {
				flash = !flash;
				flashTs = time;
			}

			if (rkBotDisabled || rkAutonMode || forceBattWarning) {
				bLCDBacklight = flash;

				clearLCD();

				if (flash) displayLCDCenteredString(0, "BATTERY WARNING");

				sprintBatt(str);
				displayLCDString(1, 0, str);

				if (fallingEdge(&dismissWarningLatch, nLCDButtons || (abs(vexRT[AccelY]) > 63))) forceBattWarning = false;

				goto waitContinue;
			}
		}

		if (rkBotDisabled || rkAutonMode) {
			bLCDBacklight = !rkBotDisabled;

			clearLCD();

			displayLCDCenteredString(0, "Moosebot Mk. II");
			displayLCDCenteredString(1, "4800Buckets");
		}
		else {
			bLCDBacklight = true;

			pwrBtns = twoWay((nLCDButtons & kButtonLeft) || vexRT[Btn5D], -flyPwrIncrement, (nLCDButtons & kButtonRight) || vexRT[Btn5U], flyPwrIncrement);

			if (pwrBtns != 0 && flyDir != 0)
				flyPwr[flyDir] = fmaxf(0, flyPwr[flyDir] + pwrBtns);

			if (flyTbh.doRun) {
				sprintf(str, "% 07.2f %d % 07.2f",
					fmaxf(-999.99, fminf(999.99, flyDiff.out)),
					flyPwr[flyDir],
					fmaxf(-999.99, fminf(999.99, flyTbh.err)));
				displayLCDString(0, 0, str);

				sprintf(str, "% 07.2f  % 07.2f",
					fmaxf(-999.99, fminf(999.99, fly2Flt.out)),
					fmaxf(-999.99, fminf(999.99, flyTbh.out)));
				displayLCDString(1, 0, str);
			}
			else {
				sprintf(str, "%-4s%6s%6s", "Spd", "Targ", "Err");
				displayLCDString(0, 0, str);

				sprintf(str, "%-8s%8s", "Accel", "Out");
				displayLCDString(1, 0, str);
			}
		}

	waitContinue:

		wait1Msec(50);
	}
}

void startFlyTbh(bool useCtl) {
	resetTbh(&flyTbh, 0);

	resetDiff(&flyDiff, 0);
	resetDiff(&fly2Diff, 0);

	resetKFlt(&fly2Flt, 0, 1);

	if (useCtl) updateTbhController(&flyCtl, 0);
	else setTbhDoRun(&flyTbh, true);

	SensorValue[flyEnc] = 0;
}

// void startLiftTbh(bool useCtl) {
  // resetTbh(&liftTbh, 0);

  // resetDiff(&liftDiff, 0);
  // resetDiff(&lift2Diff, 0);

  // if (useCtl) updateTbhController(&liftCtl, 0);
  // else setTbhDoRun(&liftTbh, true);

  // SensorValue[liftEnc] = 0;
// }

void stopCtls() {
	setTbhDoRun(&flyTbh, false);
	// setTbhDoRun(&liftTbh, false);

	stopCtlLoop();
}

void init() {
  ctlLoopInterval = 50;

  initTbh(&flyTbh, 7, kI, kD, 127, true);
  //initTbh(&liftTbh, 10, .5, 0, 127, false);

  initTbhController(&flyCtl, &flyTbh, false);
  //initTbhController(&liftCtl, &liftTbh, false);

  initKFlt(&fly2Flt, 1);

  //startTask(_lcd);
}

void updateCtl(float dt) {
	updateDiff(&flyDiff, -SensorValue[flyEnc], dt);
	updateDiff(&fly2Diff, flyDiff.out, dt);

	//updateDiff(&liftDiff, SensorValue[liftEnc], dt);
	//updateDiff(&lift2Diff, liftDiff.out, dt);

	updateKFlt(&fly2Flt, fly2Diff.out, dt);

	if (flyTbh.doUpdate)
		motor[lFly] =
			motor[rFly] =
			updateTbh(&flyTbh, flyDiff.out, fly2Flt.out, dt);

	//if (liftTbh.doUpdate)
		//motor[lift] = updateTbh(&liftTbh, -liftDiff.out, -lift2Diff.out, dt);
}

task auton() {
	const float recoilThresh = 40;

	startFlyTbh(false);
	startCtlLoop();

	setTbh(&flyTbh, autonFlyPwr);

#ifdef USE_PRELOAD_AUTON
	block(!(isTbhInThresh(&flyTbh, velThresh) &&
		isTbhDerivInThresh(&flyTbh, accelThresh)));

	while (true) {
		motor[intake] = motor[lift] = 80;

		block(isTbhInThresh(&flyTbh, recoilThresh) &&
			isTbhDerivInThresh(&flyTbh, accelThresh));

		motor[intake] = motor[lift] = 0;

		block(!(isTbhInThresh(&flyTbh, velThresh) &&
			isTbhDerivInThresh(&flyTbh, accelThresh)));

		wait1Msec(20);
	}
#else
	motor[intake] = motor[lift] = 127;
#endif
}

void endAuton() {
	stopCtls();
}

task userOp() {
	startFlyTbh(true);
	startCtlLoop();

	const float cutFac = 3;

	DLatch cutLatch, flipLatch, tankLatch, flyLRLatch, flyMRLatch, flySRLatch, flyOffLatch;

	word driveA, driveB;

#define driveX driveA
#define driveY driveB
#define driveL driveA
#define driveR driveB

	resetDLatch(&cutLatch, 0);
	resetDLatch(&flipLatch, 0);
	resetDLatch(&tankLatch, 0);
	resetDLatch(&flyLRLatch, 0);
	resetDLatch(&flyMRLatch, 0);
	resetDLatch(&flySRLatch, 0);
	resetDLatch(&flyOffLatch, 0);

	while (true) {
		risingBistable(&flipLatch, vexRT[Btn8D]);

		if (risingBistable(&tankLatch, vexRT[Btn8L])) {
			driveL = vexRT[ChLY];
			driveR = vexRT[ChRY];

			if (flipLatch.out) {
				driveL ^= driveR;
				driveR ^= driveL;
				driveL ^= driveR;

				driveL *= -1;
				driveR *= -1;
			}
		}
		else {
			driveX = vexRT[ChRX];
			driveY = vexRT[ChLY];

			if (flipLatch.out) driveY *= -1;
		}

		if (tankLatch.out) {
			tank4(driveL, driveR, flWheel, blWheel, frWheel, brWheel);
			tank2(driveL, driveR, mlWheel, mrWheel);
		}
		else {
			arcade4(driveX, driveY, flWheel, blWheel, frWheel, brWheel);
			arcade2(driveX, driveY, mlWheel, mrWheel);
		}

		if (risingEdge(&flyLRLatch, vexRT[Btn7U]))
			flyDir = 3;

		if (risingEdge(&flyMRLatch, vexRT[Btn7L]))
			flyDir = 2;

		if (risingEdge(&flySRLatch, vexRT[Btn7D]))
			flyDir = 1;

		if (risingEdge(&flyOffLatch, vexRT[Btn7R]))
			flyDir = 0;

		updateTbhController(&flyCtl, flyPwr[flyDir]);

		motor[intake] =
			joyDigi2(Btn6U, 127, Btn8U, -127);

		motor[lift] =
			joyDigi2(Btn6U, 127, Btn6D, -127);

		wait1Msec(25);
	}

#undef driveX
#undef driveY
#undef driveL
#undef driveR
}

void endUserOp() {
	stopCtls();
}
